package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/hashicorp/yamux"
	"github.com/wseternal/ssetunnel/internal/auth"
	"github.com/wseternal/ssetunnel/internal/transport"
)

// forcedTargetKey is a context key that ShellConnectHandler uses to pass
// the forced target (__shell__) to handleConnect without going through
// query parameters (which would fail agent config validation).
type forcedTargetKeyType struct{}

var forcedTargetKey = forcedTargetKeyType{}

// TargetShell is the magic target name that tells the agent to spawn
// an interactive shell with a PTY instead of dialing a TCP address.
// Must match the constant in the agent package.
const TargetShell = "__shell__"

// ShellConnectHandler returns an http.Handler that serves the cloud shell
// connect endpoint (SSE downstream). It creates or reattaches to a
// persistent shell session that survives client disconnect.
//
// Query parameters:
//   - agent: required, the target agent ID
//   - id: required, the connect session ID (random, generated by the client)
//   - reattach: optional, ID of an existing session to reattach to
//
// When reattach is set (or an existing session is found for the user+agent
// pair), the handler replays the ring buffer as SSE frames and then
// continues live streaming. Otherwise, a new yamux stream is opened.
//
// When the client disconnects, the session is detached (not destroyed) —
// the yamux stream stays alive and output continues buffering.
func (h *Handler) ShellConnectHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Validate user session auth.
		sessInfo := UserSessionFromContext(r)
		if sessInfo == nil {
			http.Error(w, "Unauthorized: user session required", http.StatusUnauthorized)
			return
		}

		q := r.URL.Query()
		agentID := q.Get("agent")
		if agentID == "" {
			http.Error(w, "agent query parameter is required", http.StatusBadRequest)
			return
		}
		id := q.Get("id")
		if id == "" {
			http.Error(w, "missing id", http.StatusBadRequest)
			return
		}

		// User-scoped access: non-admin users can only shell into their own agents.
		if !isAdmin(sessInfo) {
			if !h.agentOwnedByUser(agentID, sessInfo.UserID) {
				http.Error(w, "agent not found or access denied", http.StatusNotFound)
				return
			}
		}

		// Check for existing persistent session to reattach to.
		reattachID := q.Get("reattach")
		var ss *ShellSession

		if reattachID != "" {
			// Explicit reattach by session ID.
			ss = h.shellSessions.Load(reattachID)
			if ss == nil || ss.IsDead() {
				http.Error(w, "shell session not found or expired", http.StatusNotFound)
				return
			}
			// Verify ownership.
			if !isAdmin(sessInfo) && ss.UserID() != sessInfo.UserID {
				http.Error(w, "access denied", http.StatusForbidden)
				return
			}
		} else {
			// Check for an existing session for this user+agent pair.
			ss = h.shellSessions.FindByUserAgent(sessInfo.UserID, agentID)
		}

		if ss != nil && !ss.IsDead() {
			// Reattach to existing persistent session.
			h.shellReattach(w, r, ss, id, sessInfo)
			return
		}

		// Create a new persistent shell session.
		h.shellCreate(w, r, agentID, id, sessInfo)
	})
}

// shellReattach reattaches a client to an existing persistent shell session.
// It registers the session's up-pipe in connectSessions (so connect-up works),
// calls Attach to replay buffer + stream, and blocks until disconnect.
func (h *Handler) shellReattach(w http.ResponseWriter, r *http.Request, ss *ShellSession, connectID string, sessInfo *auth.UserSessionInfo) {
	f, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "streaming unsupported", http.StatusInternalServerError)
		return
	}

	// Register the persistent session's up-pipe as a connectSession
	// so that POST /connect-up and POST /connect-resize can find it.
	cs := &connectSession{
		id:      connectID,
		agentID: ss.AgentID(),
		userID:  ss.UserID(),
		up:      ss.UpPipe(),
		resize:  make(chan windowSize, 1),
		cancel:  func() {},
	}
	h.connectSessions.Store(connectID, cs)
	defer h.connectSessions.Delete(connectID)

	// Set SSE response headers.
	w.Header().Set("X-SSET-Session", connectID)
	w.Header().Set("X-SSET-Shell-Session", ss.ID())
	transport.WriteHeaders(w)
	f.Flush()

	// Attach: atomically drains ring buffer as SSE + sets live writer.
	if err := ss.Attach(w, f); err != nil {
		http.Error(w, fmt.Sprintf("attach: %v", err), http.StatusConflict)
		return
	}

	// Block until client disconnects.
	<-r.Context().Done()

	// Detach: session stays alive, output continues buffering.
	ss.Detach()
}

// shellCreate opens a new yamux stream to the agent, creates a persistent
// ShellSession, and attaches the client. On disconnect, the session is
// detached (not destroyed).
func (h *Handler) shellCreate(w http.ResponseWriter, r *http.Request, agentID, connectID string, sessInfo *auth.UserSessionInfo) {
	f, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "streaming unsupported", http.StatusInternalServerError)
		return
	}

	// Find the target agent's yamux session.
	const connectWaitTimeout = 3 * time.Second
	const connectPollInterval = 25 * time.Millisecond
	var ms *yamux.Session
	var agentSess *Session
	deadline := time.Now().Add(connectWaitTimeout)
	for {
		ms, agentSess = h.findYamuxByAgentID(agentID)
		if ms != nil && !ms.IsClosed() {
			break
		}
		if time.Now().After(deadline) || r.Context().Err() != nil {
			http.Error(w, fmt.Sprintf("agent %q not connected", agentID), http.StatusNotFound)
			return
		}
		time.Sleep(connectPollInterval)
	}

	// Narrow TOCTOU: re-check session alive before opening stream.
	if ms.IsClosed() {
		http.Error(w, "agent session replaced, retry", http.StatusServiceUnavailable)
		return
	}

	// Open a yamux stream to the agent.
	stream, err := ms.OpenStream()
	if err != nil {
		http.Error(w, fmt.Sprintf("open stream: %v", err), http.StatusServiceUnavailable)
		return
	}

	// Write target header (__shell__).
	if agentSess != nil && agentSess.WantTarget() {
		if _, err := fmt.Fprintf(stream, "%s\n", TargetShell); err != nil {
			stream.Close()
			http.Error(w, fmt.Sprintf("write target header: %v", err), http.StatusInternalServerError)
			return
		}
	}

	// Create the persistent shell session.
	ss := NewShellSession(connectID, agentID, sessInfo.UserID, stream)
	h.shellSessions.Store(ss)
	ss.Start(h.heartbeat)

	// Register in connectSessions for connect-up/connect-resize compatibility.
	cs := &connectSession{
		id:      connectID,
		agentID: agentID,
		userID:  sessInfo.UserID,
		up:      ss.UpPipe(),
		resize:  make(chan windowSize, 1),
		cancel:  func() {},
	}
	h.connectSessions.Store(connectID, cs)

	// Monitor agent session death to close the shell session promptly.
	if agentSess != nil {
		go func() {
			select {
			case <-agentSess.Done():
				ss.Close()
			case <-ss.Done():
			}
		}()
	}

	// Set SSE response headers.
	w.Header().Set("X-SSET-Session", connectID)
	w.Header().Set("X-SSET-Shell-Session", ss.ID())
	transport.WriteHeaders(w)
	f.Flush()

	// Attach: drains buffer (empty for new session) + sets live writer.
	if err := ss.Attach(w, f); err != nil {
		h.connectSessions.Delete(connectID)
		ss.Close()
		h.shellSessions.Delete(connectID)
		http.Error(w, fmt.Sprintf("attach: %v", err), http.StatusConflict)
		return
	}

	// Block until client disconnects.
	<-r.Context().Done()

	// Detach: session stays alive for potential reattach.
	// Unregister from connectSessions (input won't arrive without a client).
	h.connectSessions.Delete(connectID)
	ss.Detach()
}

// ShellConnectUpHandler returns an http.Handler that serves the cloud shell
// upstream POST endpoint. It delegates directly to handleConnectUp which
// uses the connect session's own auth (X-SSET-Session header).
func (h *Handler) ShellConnectUpHandler() http.Handler {
	return http.HandlerFunc(h.handleConnectUp)
}

// ShellConnectResizeHandler returns an http.Handler that serves the cloud
// shell resize POST endpoint. It delegates to handleConnectResize which
// looks up the connect session by ID from the JSON request body.
func (h *Handler) ShellConnectResizeHandler() http.Handler {
	return http.HandlerFunc(h.handleConnectResize)
}

// ShellSessionListHandler returns an http.Handler that lists active shell
// sessions for the authenticated user. Admin users see all sessions.
func (h *Handler) ShellSessionListHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		sessInfo := UserSessionFromContext(r)
		if sessInfo == nil {
			http.Error(w, "Unauthorized: user session required", http.StatusUnauthorized)
			return
		}

		type sessionInfo struct {
			ID            string `json:"id"`
			AgentID       string `json:"agent_id"`
			CreatedAt     string `json:"created_at"`
			Attached      bool   `json:"attached"`
			BufferedBytes int    `json:"buffered_bytes"`
		}

		sessions := []sessionInfo{}
		h.shellSessions.Range(func(ss *ShellSession) bool {
			// Non-admin users only see their own sessions.
			if !isAdmin(sessInfo) && ss.UserID() != sessInfo.UserID {
				return true
			}
			sessions = append(sessions, sessionInfo{
				ID:            ss.ID(),
				AgentID:       ss.AgentID(),
				CreatedAt:     ss.CreatedAt().Format("2006-01-02T15:04:05Z07:00"),
				Attached:      ss.Attached(),
				BufferedBytes: ss.BufferedBytes(),
			})
			return true
		})

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(sessions)
	})
}

// ShellSessionDeleteHandler returns an http.Handler that explicitly
// terminates a persistent shell session. User-scoped: non-admin users
// can only delete their own sessions.
func (h *Handler) ShellSessionDeleteHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete && r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		sessInfo := UserSessionFromContext(r)
		if sessInfo == nil {
			http.Error(w, "Unauthorized: user session required", http.StatusUnauthorized)
			return
		}

		var req struct {
			ID string `json:"id"`
		}
		if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, 1024)).Decode(&req); err != nil {
			http.Error(w, "bad request body", http.StatusBadRequest)
			return
		}
		if req.ID == "" {
			http.Error(w, "missing id", http.StatusBadRequest)
			return
		}

		ss := h.shellSessions.Load(req.ID)
		if ss == nil || ss.IsDead() {
			http.Error(w, "shell session not found", http.StatusNotFound)
			return
		}

		// Verify ownership.
		if !isAdmin(sessInfo) && ss.UserID() != sessInfo.UserID {
			http.Error(w, "access denied", http.StatusForbidden)
			return
		}

		h.shellSessions.Delete(req.ID)
		ss.Close()
		w.WriteHeader(http.StatusNoContent)
	})
}

// isAdmin reports whether the user session has admin role.
func isAdmin(sessInfo *auth.UserSessionInfo) bool {
	return sessInfo != nil && auth.HasPermission(sessInfo.Role, auth.PermAdmin)
}

// agentOwnedByUser checks if any session with the given agentID belongs
// to the specified user.
func (h *Handler) agentOwnedByUser(agentID string, userID int64) bool {
	found := false
	h.reg.Range(func(s *Session) bool {
		if s.AgentID() == agentID && s.UserID() == userID {
			found = true
			return false
		}
		return true
	})
	return found
}
