-- Create "admin_sessions" table
CREATE TABLE "public"."admin_sessions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "digest" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "admin_sessions_digest_idx" to table: "admin_sessions"
CREATE UNIQUE INDEX "admin_sessions_digest_idx" ON "public"."admin_sessions" ("digest");

-- Create "pins" table
CREATE TABLE "public"."pins" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "digest" text NOT NULL,
  "role" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamptz NOT NULL,
  "used_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "pins_digest_idx" to table: "pins"
CREATE UNIQUE INDEX "pins_digest_idx" ON "public"."pins" ("digest");

-- Create "tokens" table
CREATE TABLE "public"."tokens" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "digest" text NOT NULL,
  "role" text NOT NULL,
  "description" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamptz NULL,
  "revoked_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "tokens_digest_idx" to table: "tokens"
CREATE UNIQUE INDEX "tokens_digest_idx" ON "public"."tokens" ("digest");
