-- Create "user_sessions" table
CREATE TABLE "public"."user_sessions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "digest" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id")
);
-- Create index "user_sessions_digest_idx" to table: "user_sessions"
CREATE UNIQUE INDEX "user_sessions_digest_idx" ON "public"."user_sessions" ("digest");
