-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" text NOT NULL,
  "password_hash" text NOT NULL,
  "totp_secret" text NOT NULL DEFAULT '',
  "role" text NOT NULL DEFAULT 'user',
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "disabled_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_username_idx" to table: "users"
CREATE UNIQUE INDEX "users_username_idx" ON "public"."users" ("username");
