-- Create recovery_codes table for TOTP one-time backup codes.
CREATE TABLE "public"."recovery_codes" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"     bigint NOT NULL,
    "code_digest" text NOT NULL,
    "used_at"     timestamptz NULL,
    "created_at"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "recovery_codes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE
);

-- Partial unique index on unused codes: prevents double-use at DB level and enables race-safe consumption.
CREATE UNIQUE INDEX "recovery_codes_code_digest_idx" ON "public"."recovery_codes" ("code_digest") WHERE "used_at" IS NULL;

-- Partial index on user_id for listing remaining unused codes per user.
CREATE INDEX "recovery_codes_user_id_idx" ON "public"."recovery_codes" ("user_id") WHERE "used_at" IS NULL;
