//go:build !windows

package agent

import (
	"encoding/json"
	"io"
	"log"
	"net"
	"os"
	"os/exec"
	"strings"
	"sync"
	"time"

	"github.com/creack/pty"
)

// proxyShell spawns an interactive shell with a PTY and proxies
// bidirectionally between the yamux stream and the shell's stdin/stdout.
// When the stream closes or the shell exits, both sides are torn down.
func proxyShell(stream net.Conn) {
	shell := os.Getenv("SHELL")
	if shell == "" {
		shell = "/bin/sh"
	}

	cmd := exec.Command(shell)
	// Build a clean environment with an explicit TERM=xterm-256color.
	// pty.Start appends TERM=xterm, but if os.Environ() already contains
	// a TERM entry (e.g. from the agent's parent process), the duplicate
	// may cause the shell to use the first (possibly wrong) value, which
	// can prevent ZLE from activating properly.
	env := make([]string, 0, len(os.Environ())+1)
	for _, e := range os.Environ() {
		if !strings.HasPrefix(e, "TERM=") {
			env = append(env, e)
		}
	}
	env = append(env, "TERM=xterm-256color")
	cmd.Env = env

	// Start the command with a PTY. The returned file is the master
	// side of the pseudo-terminal — reads yield shell output, writes
	// feed shell input.
	ptmx, err := pty.Start(cmd)
	if err != nil {
		log.Printf("agent: start shell %s: %v", shell, err)
		stream.Close()
		return
	}

	log.Printf("agent: shell session started (pid=%d, shell=%s)", cmd.Process.Pid, shell)

	var wg sync.WaitGroup
	wg.Add(2)

	// stream → PTY (user input + resize commands). The server multiplexes
	// regular keystrokes and NUL-prefixed JSON resize messages on the same
	// stream. NUL (\x00) cannot be generated by a terminal keyboard, making
	// it a safe delimiter for out-of-band control messages.
	//
	// When the stream closes, close the PTY master to signal EOF to the
	// shell. If the shell doesn't exit within 2 seconds (e.g., traps
	// SIGHUP), force-kill it. Killing the process closes the slave FD,
	// which causes the PTY master read in the output goroutine to return
	// EIO, unblocking it and allowing wg.Wait() to return.
	go func() {
		defer wg.Done()
		forwardStreamToPTY(stream, ptmx)
		ptmx.Close() // signal EOF to shell (sends SIGHUP)

		// Give the shell 2 seconds to exit gracefully, then force-kill.
		timer := time.NewTimer(2 * time.Second)
		defer timer.Stop()
		select {
		case <-timer.C:
			cmd.Process.Kill() // force-kill: closes slave FD → unblocks output goroutine
		}
	}()

	// PTY → stream (shell output). When the shell exits or the PTY
	// closes, close the stream so the connect client sees EOF.
	go func() {
		defer wg.Done()
		io.Copy(stream, ptmx)
		stream.Close()
	}()

	wg.Wait()

	// Reap the shell process. It should already be dead (exited
	// naturally from EOF or force-killed by the input goroutine).
	cmd.Wait()
}

// forwardStreamToPTY reads from the yamux stream one byte at a time and
// writes to the PTY master. NUL bytes (\x00) signal out-of-band resize
// commands: the next bytes up to '\n' are parsed as JSON {cols, rows}
// and applied via pty.Setsize. The yamux stream has internal buffering
// so single-byte reads are efficient enough for interactive terminal I/O.
func forwardStreamToPTY(stream net.Conn, ptmx *os.File) {
	one := make([]byte, 1)
	for {
		if _, err := io.ReadFull(stream, one); err != nil {
			return
		}
		if one[0] == 0 {
			if !readAndApplyResize(stream, ptmx) {
				return
			}
			continue
		}
		if _, err := ptmx.Write(one); err != nil {
			return
		}
	}
}

// readAndApplyResize reads a JSON resize message (up to '\n') from the
// stream and applies it to the PTY. Returns false if the stream is closed.
func readAndApplyResize(stream net.Conn, ptmx *os.File) bool {
	one := make([]byte, 1)
	var buf []byte
	for {
		if _, err := io.ReadFull(stream, one); err != nil {
			return false
		}
		if one[0] == '\n' {
			break
		}
		buf = append(buf, one[0])
	}
	var ws struct {
		Cols uint16 `json:"cols"`
		Rows uint16 `json:"rows"`
	}
	if err := json.Unmarshal(buf, &ws); err != nil {
		log.Printf("agent: bad resize JSON: %v", err)
	} else if err := pty.Setsize(ptmx, &pty.Winsize{
		Rows: ws.Rows,
		Cols: ws.Cols,
	}); err != nil {
		log.Printf("agent: pty resize: %v", err)
	}
	return true
}
